### PR TITLE
fix: globs in path if cwd is not the cfg file loc

### LINKED ISSUE #42: path does not working if cwd is not the cfg file location
**Describe the bug**
path does not working if cwd is not the cfg file location since path accepts glob

**To Reproduce**
1. move the mkdocs.yml into a folder, for example tools/mkdocs
2. run command mkdocs build -f ./tools/mkdocs/mkdocs.yml -d ../../site
3. See error

### PR DESCRIPTION
**Pull request by veghdev**
fix #42 

based on the documentation: "Non-absolute paths are computed as relative to MkDocs configuration file."

### CODE REVIEW

**Comment by veghdev** [comment]
I did not use the glob.glob() root_dir argument because it is only available from python 3.10.

**Comment by veghdev** [comment]
@pawamoy Could you please review? Thanks

**Comment by pawamoy** [comment]
Sure, I will when I get some time :)
Thanks for the PR!

**Comment by pawamoy** [comment]
CI failures unrelated, will fix in another PR.

I took the liberty to modify your changes a bit, I hope you don't mind.

**Comment by veghdev** [comment]
> I took the liberty to modify your changes a bit, I hope you don't mind.

No problem, I'm glad I could help and thank you for your review.

**Pull request merged**
